-- dynamic
DROP TABLE IF EXISTS public."Lexicon" CASCADE;
CREATE TABLE public."Lexicon" (
	"id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 CYCLE),
	"word_class" varchar NULL,
	"word" varchar NULL,
	"article" varchar NULL,
	"translation" varchar NULL,
    "first_letter" varchar NULL,
    "description" varchar NULL,
	"context_example" varchar NULL,
	PRIMARY KEY ("id")
);